print("My English name is Noel :")
print("#    #     ####     #####    #     ")
print("##   #    #    #    #        #     ")
print("# #  #    #    #    #####    #     ")
print("#  # #    #    #    #        #     ")
print("#    #     ####     #####    ##### ")
